// javascript/interview/vue3-app/src/pages/Home.vue
<template>
  <div class="home">
    <div class="home__items">
      <div class="number home__items__num">-5-5</div>
      <div class="number home__items__sym" />
      <div class="number home__items__num">3-9</div>
      <div class="number home__items__sym" />
      <div class="number home__items__num">1-2</div>
    </div>
    <div class="home__counters">
      <div class="counter">
        <div class="btn"><i class="minus" /></div>
        <div class="number">0</div>
        <div class="btn"><div class="plus" /></div>
      </div>
      <div class="counter">
        <div class="btn"><i class="minus" /></div>
        <div class="number">5</div>
        <div class="btn"><div class="plus" /></div>
      </div>
      <div class="counter">
        <div class="btn"><i class="minus" /></div>
        <div class="number">2</div>
        <div class="btn"><div class="plus" /></div>
      </div>
    </div>
    <div class="home__items">
      <div class="number home__items__num">0</div>
      <div class="number home__items__sym">+</div>
      <div class="number home__items__num">5</div>
      <div class="number home__items__sym">x</div>
      <div class="number home__items__num">2</div>
    </div>
    <div class="number home__result">10</div>
  </div>
</template>

// javascript/interview/react-app/src/pages/home.jsx
import React from 'react'

export { Home }

function Home() {
  return <div className="home">
    <div className="home__items">
      <div className="number home__items__num">-5-5</div>
      <div className="number home__items__sym" />
      <div className="number home__items__num">3-9</div>
      <div className="number home__items__sym" />
      <div className="number home__items__num">1-2</div>
    </div>
    <div className="home__counters">
      <div className="counter">
        <div className="btn"><i className="minus" /></div>
        <div className="number">0</div>
        <div className="btn"><div className="plus" /></div>
      </div>
      <div className="counter">
        <div className="btn"><i className="minus" /></div>
        <div className="number">5</div>
        <div className="btn"><div className="plus" /></div>
      </div>
      <div className="counter">
        <div className="btn"><i className="minus" /></div>
        <div className="number">2</div>
        <div className="btn"><div className="plus" /></div>
      </div>
    </div>
    <div className="home__items">
      <div className="number home__items__num">0</div>
      <div className="number home__items__sym">+</div>
      <div className="number home__items__num">5</div>
      <div className="number home__items__sym">x</div>
      <div className="number home__items__num">2</div>
    </div>
    <div className="number home__result">10</div>
  </div>
}
