// javascript/l8/interview/vue2-app/src/pages/Login.vue
<template>
  <div class="login">
    <div class="login__tip">尚未登入</div>
    <div class="login__content">
      <input class="input login__content__input" placeholder="只有輸入 user 才可登入" />
      <div class="btn login__content__submit">登入</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Login'
}
</script>

// javascript/interview/react-app/src/pages/login.jsx
import React from 'react'

export { Login }

function Login() {
  return <div className="login">
    <div className="login__tip">尚未登入</div>
    <div className="login__content">
      <input className="input login__content__input" placeholder="只有輸入 user 才可登入" />
      <div className="btn login__content__submit">登入</div>
    </div>
  </div>
}
